### ISSUE TITLE
Sorry, I have an installation problem.

### ISSUE THREAD

**Issue by yummy141** [swharden/PyOriginTools#1]
When I used ''pip install PyOriginTools'' on Windows 7, I failed. And the error information is ''could not find a version that satisfies the requirement swhlab>=0.1.113''. Can you help me with it?

**Comment by swharden** [comment]
It's because [swhlab](https://github.com/swharden/SWHLab) is slowly being replaced by [pyABF](https://github.com/swharden/pyABF) and I've taken down the PyPi package for swhlab.

This should get you going!
Try `pip install --no-dependencies PyOriginTools`

**Comment by yummy141** [comment]
Wow, it's solved! Thanks for your time.

**Comment by swharden** [comment]
... I added an installation note on the front page of the project, as well as a note that this project is classified as abandonware and may not be supported by new versions of OriginLab

Thanks for your initial message!
