### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by liuyun16** [swharden/PyOriginTools#2]
Hello, I'm wondering whether this module can still work?
I have tried to install it ,but what I find is:
‘’’
pip install PyOriginTools
Collecting PyOriginTools
  Downloading 
‘’’
![image](https://user-images.githubusercontent.com/24448319/39099565-44cf936e-467d-11e8-87dc-22a71256c192.png)

I am really interested with your function of "Work with Origin Data outside of Origin!", So could you please upgrade the requirements? Or do you have other better access to Origin API?
Thanks very much!

**Comment by liuyun16** [comment]
It has been solved in [Sorry, I have an installation problem. · Issue #1 · swharden/PyOriginTools](https://github.com/swharden/PyOriginTools/issues/1)

**Comment by swharden** [comment]
Hi Liuyun,

As Origin kept developing their modules and Python support, this package kept breaking. Therefore it is no longer working and no longer being developed. 

It is my hope that one day OriginLab themselves will make a usable Python module. Something with usage like this would be great:
https://github.com/swharden/PyOriginTools/blob/master/documentation/API-design/ideas.md

Unfortunately, they haven't produced something adequately documented or user friendly yet. Maybe one day!

**Comment by swharden** [comment]
... since multiple people have run into this same snag, I'll go ahead and remove "swhlab" as a dependency

**Comment by swharden** [comment]
Removed dependencies and clarified as abandonware in PyPi listing
https://github.com/swharden/PyOriginTools/commit/a1aaceb3b5f98aaa607d695bfaff051c12ee00b5

https://pypi.org/project/PyOriginTools/
